#
# This has to be added to the main routes .yaml if the default flow routes are not present
#

# -
#   name: 'Monocle'
#   uriPattern: 'sitegeist/monocle/<MonocleSubroutes>'
#   subRoutes:
#     'MonocleSubroutes':
#       package: 'Sitegeist.Monocle'


##
# Monocle

-
  name:  'Monocle API'
  uriPattern: 'monocle/api/{@action}'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@controller': 'Api'
    '@format': 'html'
  httpMethods: ['GET','POST']

-
  name:  'Monocle Mock'
  uriPattern: 'monocle/mock/{@action}'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@controller': 'Mock'
    '@format': 'text'
  httpMethods: ['GET','POST']
  appendExceedingArguments: true

-
  name:  'Monocle Preview - Module'
  uriPattern: 'monocle/preview/module'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@action': 'index'
    '@controller': 'Module'
    '@format': 'html'
  httpMethods: ['GET','POST']

-
  name:  'Monocle Preview - Module (with ignored url part)'
  uriPattern: 'monocle/preview/module/{ignore}'
  routeParts:
    'ignore':
      handler: 'Sitegeist\Monocle\Routing\IgnoreRoutePartHandler'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@action': 'index'
    '@controller': 'Module'
    '@format': 'html'
  httpMethods: ['GET','POST']

-
  name:  'Monocle Preview - Prototype'
  uriPattern: 'monocle/preview/{@action}'
  defaults:
    '@package': 'Sitegeist.Monocle'
    '@subpackage': ''
    '@controller': 'Preview'
    '@format': 'html'
  httpMethods: ['GET','POST']
  appendExceedingArguments: true
